server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: funciones-service
          uri: lb://funciones-service
          predicates:
            - Path=/funciones/**
        - id: peliculas-service
          uri: lb://peliculas-service
          predicates:
            - Path=/peliculas/**
        - id: tickets-service
          uri: lb://tickets-service
          predicates:
            - Path=/tickets/**